apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-llm-benchmarks

namePrefix: llm-d-granite-

resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: guidellm-benchmark
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "http://openshift-ai-inference-openshift-default.openshift-ingress.svc.cluster.local/demo-llm/granite/v1"
      - op: replace
        path: /spec/template/spec/containers/0/env/6/value
        value: "ibm-granite/granite-3.3-8b-instruct"
      - op: replace
        path: /spec/template/spec/volumes/2/persistentVolumeClaim/claimName
        value: "benchmark-data"
