apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-network-operator-ibm-cloud
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: llm-d-playbooks
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nvidia-network-operator
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://github.com/llm-d/llm-d-playbooks.git
    targetRevision: main
    path: 05-ocp-accelerator-operators/14-nvidia-network-operator/overlays/ibm-cloud
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 8
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
